version: 2
updates:
  - package-ecosystem: npm
    directory: "/backend/signaling"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: cargo
    directory: "/core_crypto"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      cargo-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: gradle
    directory: "/client_android"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      gradle-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
