version: 2
updates:
  - package-ecosystem: npm
    directory: "/backend/signaling"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: "/core_crypto"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: "/client_android"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
