[Interface]
PrivateKey = <REDACTED — see ~/Documents/SecureCall-Release/>
Address = 10.99.0.2/31
DNS = 1.1.1.1

[Peer]
PublicKey = ui2z9Yb81/PhUPFNP84ZTI7DhFo5PjZAEzVwkKtNGU4=
Endpoint = 192.168.1.104:51821
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
