[Interface]
PrivateKey = <REDACTED — see ~/Documents/SecureCall-Release/>
Address = 10.99.0.1/31
ListenPort = 51821

[Peer]
PublicKey = mrnczWhlyGEMZDtTBgYQ6RPTznrw3YJQ24FsGF9bhDM=
AllowedIPs = 10.99.0.2/32
