package com.securecall.app.billing

import okio.ByteString.Companion.decodeBase64
import org.junit.Assert.assertEquals
import org.junit.Test

class NodeEntitlementCompatibilityTest {
    @Test
    fun verifiesActualNodeIssuerUnpaddedToken() {
        // Generated by the repository's Node issuer with an ephemeral fixture key.
        // The private key was discarded; this is neither a sale nor a live license.
        val publicKey = "OYNKXE-2hnueEC7jVWyQRnKBIcGXGmsY9aUuDB6G4yQ".decodeBase64()!!.toByteArray()
        val token = "dj0yCmlzcz1zdGVhbHRoeAphdWQ9c2VjdXJlY2FsbApzdWI9YW5kcm9pZC1saWNlbnNlLWZpeHR1cmUKdGllcj1QUk8KcHJvZHVjdD12bGFic19zZWN1cmVjYWxsX3Byb19saWZldGltZQppYXQ9MTcwMDAwMDAwMApleHA9MTcwMjU5MjAwMApvcmRlcj0yOGJkN2U4YWI5MzFmOGNiYjJlODgzMWMzYjYwYjRkMQpjYXRhbG9nPXN0ZWFsdGh4LWxpZmV0aW1lLXYxCm9mZmVyPXNlY3VyZWNhbGwtcHJvLWV1ci0xNTAwLWxpZmV0aW1lLXYxCnJlbGVhc2U9c2VjdXJlY2FsbC1hbmRyb2lkLTEuMC41MC12Yzc4MDE3LWFwaTM2.uBAzdp4RwTrS0eIg8G4dHEyPTfiqC7eTiOOBSFOrbWjLHm1aeSkftWjpcBwTEVWTRJMRY9aVgm4xm_voHfGICg"
        val result = DirectEntitlementVerifier.verify(token, publicKey, "android-license-fixture", "PRO",
            "securecall-android-1.0.50-vc78017-api36", 1700000001)
        assertEquals("PRO", result.tier)
        assertEquals(1702592000L, result.expiresAtEpochSeconds)
    }
}
