---
name: Basic CI

on:
  push:
    branches: ["main", "dev", "feature/**"]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    name: Lint Markdown & YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install linters
        run: |
          pip install yamllint

      - name: Run YAML Lint
        run: yamllint .
